[build]
  # Onde a Netlify deve procurar os arquivos para publicar (seu frontend)
  publish = "public"
  # Onde estão suas funções de servidor
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200